// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/admin" | "/admin-dashboard" | "/admin/admins" | "/admin/availability" | "/admin/inventory" | "/admin/menu" | "/admin/offers" | "/admin/orders" | "/admin/quotes" | "/breakfast-box" | "/cake-studio" | "/cake-tracking/[code]" | "/cart-checkout" | "/login" | "/menu-browser" | "/order-history" | "/order-management" | "/order-status/[orderId]" | "/register" | "/sweet-box-builder" | "/track-order"
type AppRouteHandlerRoutes = "/api/admin/blocked-days" | "/api/admin/inventory" | "/api/ai/image-generation" | "/api/availability" | "/api/cron/cleanup-cakes" | "/api/notify-status" | "/api/orders" | "/api/stable-horde" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/admin": {}
  "/admin-dashboard": {}
  "/admin/admins": {}
  "/admin/availability": {}
  "/admin/inventory": {}
  "/admin/menu": {}
  "/admin/offers": {}
  "/admin/orders": {}
  "/admin/quotes": {}
  "/api/admin/blocked-days": {}
  "/api/admin/inventory": {}
  "/api/ai/image-generation": {}
  "/api/availability": {}
  "/api/cron/cleanup-cakes": {}
  "/api/notify-status": {}
  "/api/orders": {}
  "/api/stable-horde": {}
  "/auth/callback": {}
  "/breakfast-box": {}
  "/cake-studio": {}
  "/cake-tracking/[code]": { "code": string; }
  "/cart-checkout": {}
  "/login": {}
  "/menu-browser": {}
  "/order-history": {}
  "/order-management": {}
  "/order-status/[orderId]": { "orderId": string; }
  "/register": {}
  "/sweet-box-builder": {}
  "/track-order": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
