// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/admins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/admins">> = Specific
  const handler = {} as typeof import("../../src/app/admin/admins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/availability">> = Specific
  const handler = {} as typeof import("../../src/app/admin/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/admin/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu">> = Specific
  const handler = {} as typeof import("../../src/app/admin/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/offers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/quotes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/breakfast-box/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/breakfast-box">> = Specific
  const handler = {} as typeof import("../../src/app/breakfast-box/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cake-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cake-studio">> = Specific
  const handler = {} as typeof import("../../src/app/cake-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cake-tracking/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cake-tracking/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/cake-tracking/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cart-checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart-checkout">> = Specific
  const handler = {} as typeof import("../../src/app/cart-checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/menu-browser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu-browser">> = Specific
  const handler = {} as typeof import("../../src/app/menu-browser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/order-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-history">> = Specific
  const handler = {} as typeof import("../../src/app/order-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/order-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-management">> = Specific
  const handler = {} as typeof import("../../src/app/order-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/order-status/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-status/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/order-status/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sweet-box-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sweet-box-builder">> = Specific
  const handler = {} as typeof import("../../src/app/sweet-box-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/track-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track-order">> = Specific
  const handler = {} as typeof import("../../src/app/track-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/blocked-days/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blocked-days">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/blocked-days/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/image-generation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/image-generation">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/image-generation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/availability">> = Specific
  const handler = {} as typeof import("../../src/app/api/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/cleanup-cakes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/cleanup-cakes">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/cleanup-cakes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notify-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/notify-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stable-horde/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stable-horde">> = Specific
  const handler = {} as typeof import("../../src/app/api/stable-horde/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
